### PR TITLE
Remove user agent stylesheets' blue outline from from preview back and forward buttons

### PR DESCRIPTION
**Pull request by metarmask**
screenshot 2015-01-20 at 21 57 58

### CODE REVIEW

**Comment by ezfe** [comment]
What browser are you using that would do this?

**Comment by ezfe** [comment]
Isn't this your browser or system settings, though?

**Comment by ezfe** [comment]
Wouldn't it make sense to observe the settings as set system wide?

**Comment by metarmask** [comment]
Yes, that's the less fancy way of saying "user agent stylesheet". It's basically a default stylesheet for a browser.

There is no way to change this (without going back to chrome v32 and replacing a file called Custom.css)

**Pull request merged**
